import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import path from "path"
import type { Plugin } from 'rolldown'

// When Vite pre-bundles recharts it encounters es-toolkit/compat/* sub-paths
// (e.g. es-toolkit/compat/get). Those sub-paths resolve to CJS wrapper files
// whose local variable names (require_isUnsafeProperty, …) were generated by
// rollup and collide with the dep optimizer's own CJS→ESM wrapper names,
// causing "require_isUnsafeProperty is not a function" at runtime.
//
// Fix: intercept those sub-path imports during dep optimization and re-route
// them to the proper ESM bundle (es-toolkit/compat → dist/compat/index.mjs).
// The main compat bundle has no CJS and no naming collision.
const esToolkitCompatShimPlugin: Plugin = {
  name: 'es-toolkit-compat-shim',
  resolveId(source) {
    if (/^es-toolkit\/compat\/.+/.test(source)) {
      return { id: `\0es-toolkit-compat-shim:${source}` }
    }
  },
  load(id) {
    if (id.startsWith('\0es-toolkit-compat-shim:')) {
      const name = id.slice('\0es-toolkit-compat-shim:es-toolkit/compat/'.length)
      return `export { ${name} as default } from 'es-toolkit/compat'`
    }
  },
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), tailwindcss()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  optimizeDeps: {
    include: ["recharts"],
    rolldownOptions: {
      plugins: [esToolkitCompatShimPlugin],
    },
  },
  server:{
    allowedHosts:[
      "borax-stupor-refract.ngrok-free.dev",
    ]
  }
})
