import { defineConfig, type Plugin } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import path from "path"

// When Vite pre-bundles recharts it encounters es-toolkit/compat/* sub-paths
// (e.g. es-toolkit/compat/get). Those sub-paths resolve to CJS wrapper files
// whose local variable names (require_isUnsafeProperty, …) were generated by
// rollup and collide with the dep optimizer's own CJS→ESM wrapper names,
// causing "require_isUnsafeProperty is not a function" at runtime.
//
// Fix: intercept those sub-path imports during dep optimization and re-route
// them to the proper ESM bundle (es-toolkit/compat → dist/compat/index.mjs).
// The main compat bundle has no CJS and no naming collision.
const esToolkitCompatShimPlugin: Plugin = {
  name: 'es-toolkit-compat-shim',
  enforce: 'pre',
  resolveId(source) {
    if (/^es-toolkit\/compat\/.+/.test(source)) {
      return { id: `\0es-toolkit-compat-shim:${source}` }
    }
  },
  load(id) {
    if (id.startsWith('\0es-toolkit-compat-shim:')) {
      const name = id.slice('\0es-toolkit-compat-shim:es-toolkit/compat/'.length)
      return `export { ${name} as default } from 'es-toolkit/compat'`
    }
  },
}

// https://vite.dev/config/
export default defineConfig({
  // Registered at the top level so it also runs during the production build
  // (optimizeDeps only pre-bundles for the dev server, not `vite build`).
  plugins: [react(), tailwindcss(), esToolkitCompatShimPlugin],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  // sockjs-client (bc-notifications WebSocket transport, see useNotificationSocket) is a
  // Node-oriented CJS package that references the bare `global` — undefined in a browser.
  // Webpack shims this automatically; Vite/esbuild don't, hence the ReferenceError at
  // runtime. Mapping it to `globalThis` (available in every modern browser) is the
  // standard fix, without pulling in a full node-polyfills plugin for this one symbol.
  define: {
    global: "globalThis",
  },
  optimizeDeps: {
    include: ["recharts"],
    rolldownOptions: {
      plugins: [esToolkitCompatShimPlugin],
    },
  },
  server:{
    allowedHosts:[
      "borax-stupor-refract.ngrok-free.dev",
    ]
  }
})
