import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import path from "path"

// When esbuild pre-bundles recharts it encounters es-toolkit/compat/* sub-paths
// (e.g. es-toolkit/compat/get). Those sub-paths resolve to CJS wrapper files
// whose local variable names (require_isUnsafeProperty, …) were generated by
// rollup and collide with esbuild's own CJS→ESM wrapper names, causing
// "require_isUnsafeProperty is not a function" at runtime.
//
// Fix: intercept those sub-path imports inside esbuild and re-route them to
// the proper ESM bundle (es-toolkit/compat → dist/compat/index.mjs).
// The main compat bundle has no CJS and no naming collision.
const esToolkitCompatEsbuildPlugin = {
  name: 'es-toolkit-compat-shim',
  setup(build: import('esbuild').PluginBuild) {
    build.onResolve(
      { filter: /^es-toolkit\/compat\/.+/ },
      (args: import('esbuild').OnResolveArgs) => ({
        path: args.path.replace(/^es-toolkit\/compat\//, ''),
        namespace: 'es-toolkit-compat-shim',
      })
    )
    build.onLoad(
      { filter: /.*/, namespace: 'es-toolkit-compat-shim' },
      (args: import('esbuild').OnLoadArgs) => ({
        contents: `export { ${args.path} as default } from 'es-toolkit/compat'`,
        resolveDir: path.resolve(__dirname, 'node_modules'),
      })
    )
  },
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), tailwindcss()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  optimizeDeps: {
    include: ["recharts"],
    esbuildOptions: {
      plugins: [esToolkitCompatEsbuildPlugin],
    },
  },
})
