// Fixtures for forfaitApi.getAll() — see the VITE_MOCK_CLIENT_DATA flag in forfaitApi.ts.
// Two sites (site-mock-01 / site-mock-02, same ids as routeurApi.mock.ts) with a small
// catalog each, covering a range of durations/volumes/prices for the "acheter un forfait"
// grid (ForfaitsAchatPage) and the summary shown on PaiementPage/ConfirmationPage.
import type { Forfait } from "../types";

export const mockForfaits: Forfait[] = [
  {
    id: "prod-mock-01",
    name: "Pass 1 Heure",
    description: "Idéal pour une navigation rapide",
    price: 200,
    currency: "XAF",
    durationMinutes: 60,
    dataVolumeMb: 500,
    maxConcurrentDevices: 1,
    active: true,
    siteIds: ["site-mock-01"],
  },
  {
    id: "prod-mock-02",
    name: "Pass Journée",
    description: "Accès illimité en temps pendant 24h",
    price: 500,
    currency: "XAF",
    durationMinutes: 1440,
    dataVolumeMb: 2000,
    maxConcurrentDevices: 2,
    active: true,
    siteIds: ["site-mock-01"],
  },
  {
    id: "prod-mock-03",
    name: "Pass Semaine",
    description: "Pour les séjours prolongés",
    price: 2000,
    currency: "XAF",
    durationMinutes: 10080,
    dataVolumeMb: 10000,
    maxConcurrentDevices: 3,
    active: true,
    siteIds: ["site-mock-01"],
  },
  {
    id: "prod-mock-04",
    name: "Pass Réunion",
    description: "3h de connexion, parfait pour une réunion",
    price: 350,
    currency: "XAF",
    durationMinutes: 180,
    dataVolumeMb: 1000,
    maxConcurrentDevices: 1,
    active: false,
    siteIds: ["site-mock-01"],
  },
  {
    id: "prod-mock-05",
    name: "Pass 1 Heure",
    description: "Idéal pour une navigation rapide",
    price: 200,
    currency: "XAF",
    durationMinutes: 60,
    dataVolumeMb: 500,
    maxConcurrentDevices: 1,
    active: true,
    siteIds: ["site-mock-02"],
  },
  {
    id: "prod-mock-06",
    name: "Pass Journée",
    description: "Accès illimité en temps pendant 24h",
    price: 500,
    currency: "XAF",
    durationMinutes: 1440,
    dataVolumeMb: 2000,
    maxConcurrentDevices: 2,
    active: true,
    siteIds: ["site-mock-02"],
  },
];
